const bikeData = [
    // Mountain Bikes
    {
      id: 1,
      name: "Summit X-Trail 700",
      image: "/products/summit-xtrail-700.jpg",
      description: "A rugged mountain bike designed for extreme terrains and adventurous trails.",
      price: 799.99,
      rating: 4.7,
      category: "Mountain",
      featured: true,
    },
    {
      id: 2,
      name: "RockRider Pro",
      image: "/products/rockrider-pro.jpg",
      description: "An all-terrain mountain bike with precision handling and durable frame.",
      price: 649.99,
      rating: 4.6,
      category: "Mountain",
      featured: false,
    },
    {
      id: 3,
      name: "Alpine Breaker 500",
      image: "/products/alpine-breaker-500.jpg",
      description: "Perfect for steep climbs and thrilling descents, built with lightweight materials.",
      price: 729.99,
      rating: 4.8,
      category: "Mountain",
      featured: false,
    },
  
    // Electric Bikes
    {
      id: 4,
      name: "Volt Runner",
      image: "/products/volt-runner.jpg",
      description: "A powerful electric bike with a long-lasting battery and sleek design.",
      price: 1299.99,
      rating: 4.9,
      category: "Electric",
      featured: false,
    },
    {
      id: 5,
      name: "Eagle Glide Plus",
      image: "/products/eagle-glide-plus.jpg",
      description: "Smooth and efficient, this e-bike is perfect for urban commutes and light trails.",
      price: 1199.99,
      rating: 4.7,
      category: "Electric",
      featured: true,
    },
    {
      id: 6,
      name: "ThunderFlash E-Bike",
      image: "/products/thunderflash-ebike.jpg",
      description: "Combining speed and performance, the ThunderFlash is ideal for e-bike enthusiasts.",
      price: 1499.99,
      rating: 4.8,
      category: "Electric",
      featured: true,
    },
  
    // City Bikes
    {
      id: 7,
      name: "Metro Cruiser 300",
      image: "/products/metro-cruiser-300.jpg",
      description: "A comfortable and stylish bike perfect for city streets and leisure rides.",
      price: 449.99,
      rating: 4.5,
      category: "City",
      featured: false,
    },
    {
      id: 8,
      name: "UrbanFlex Commuter",
      image: "/products/urbanflex-commuter.jpg",
      description: "A sleek commuter bike with a lightweight frame and premium components.",
      price: 599.99,
      rating: 4.7,
      category: "City",
      featured: true,
    },
    {
      id: 9,
      name: "CitiFlow 200",
      image: "/products/citiflow-200.jpg",
      description: "A reliable bike designed for everyday city commutes and casual weekend rides.",
      price: 499.99,
      rating: 4.6,
      category: "City",
      featured: true,
    },
  
    // Accessories
    {
      id: 10,
      name: "TrailBlazer Helmet",
      image: "/products/trailblazer-helmet.jpg",
      description: "A lightweight, durable helmet with advanced ventilation and safety features.",
      price: 59.99,
      rating: 4.8,
      category: "Accessories",
      featured: true,
    },
    {
      id: 11,
      name: "TurboAir Tire Pump",
      image: "/products/turboair-tire-pump.jpg",
      description: "A high-pressure tire pump with an ergonomic handle and precise gauge for quick inflation.",
      price: 39.99,
      rating: 4.7,
      category: "Accessories",
      featured: false,
    },
    {
      id: 12,
      name: "ChimePro Bike Bell",
      image: "/products/chimepro-bike-bell.jpg",
      description: "A sleek and loud bike bell with a modern design, perfect for urban and trail biking.",
      price: 14.99,
      rating: 4.5,
      category: "Accessories",
      featured: false,
    },
  ];
  
  export default bikeData;