const servicesData = [
    {
      id: 1,
      name: "Basic Tune-Up",
      image: "/services/basic-tune-up.jpg",
      description: "Keep your bike in top condition with a basic tune-up service.",
      featured: true,
      priceRange: "$40 - $60",
    },
    {
      id: 2,
      name: "Flat Tire Repair",
      image: "/services/flat-tire-repair.jpg",
      description: "Quick and reliable flat tire repairs for all different bike types.",
      featured: false,
      priceRange: "$10 - $20",
    },
    {
      id: 3,
      name: "Brake Adjustment",
      image: "/services/brake-adjustment.jpg",
      description: "Ensure optimal braking performance with our adjustment services.",
      featured: true,
      priceRange: "$25 - $50",
    },
    {
      id: 4,
      name: "Full Overhaul",
      image: "/services/full-overhaul.jpg",
      description: "Comprehensive bike servicing for peak performance and optimal output.",
      featured: false,
      priceRange: "$100 - $200",
    },
    {
      id: 5,
      name: "Gear Adjustment",
      image: "/services/gear-adjustment.jpg",
      description: "Smooth and precise gear shifting with our adjustment services.",
      featured: true,
      priceRange: "$30 - $70",
    },
    {
      id: 6,
      name: "Chain Replacement",
      image: "/services/chain-replacement.jpg",
      description: "Replace worn-out chains to maintain bike efficiency and increase longevity.",
      featured: false,
      priceRange: "$20 - $50",
    },
    {
      id: 7,
      name: "Wheel Truing",
      image: "/services/wheel-truing.jpg",
      description: "Align your bike wheels for a smooth ride wherever you decide to go.",
      featured: true,
      priceRange: "$30 - $60",
    },
    {
      id: 8,
      name: "Suspension Service",
      image: "/services/suspension-service.jpg",
      description: "Optimize your bike's suspension for comfort and control for a relaxing ride.",
      featured: false,
      priceRange: "$80 - $150",
    },
    {
      id: 9,
      name: "Bike Fitting",
      image: "/services/bike-fitting.jpg",
      description: "Get professionally fitted to your bike for maximum comfort for all sizes.",
      featured: true,
      priceRange: "$50 - $100",
    },
    {
      id: 10,
      name: "Handlebar Adjustment",
      image: "/services/handlebar-adjustment.jpg",
      description: "Personalize your handlebar for better ergonomics to protect your hands.",
      featured: false,
      priceRange: "$15 - $40",
    },
    {
      id: 11,
      name: "Hydraulic Brake Bleed",
      image: "/services/hydraulic-brake-bleed.jpg",
      description: "Maintain hydraulic braking performance with our bleeding services.",
      featured: true,
      priceRange: "$40 - $80",
    },
    {
      id: 12,
      name: "Custom Bike Build",
      image: "/services/custom-bike-build.jpg",
      description: "Create your dream bike with our custom build services.",
      featured: false,
      priceRange: "$200 - $500",
    },
  ];
  
  export default servicesData;